ansh_dbt_youtube:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: dbc-c9b6ac07-9821.cloud.databricks.com
      http_path: /sql/1.0/warehouses/b5e589c26ed8798f
      schema: default
      threads: 1
      token:
      type: databricks
    prod:
      catalog: dbt_tutorial_prod
      host: dbc-c9b6ac07-9821.cloud.databricks.com
      http_path: /sql/1.0/warehouses/b5e589c26ed8798f
      schema: default
      threads: 1
      token:
      type: databricks
  target: dev